<h1>Login</h1>
<form method="POST">
	<input type="hidden" name="action" value="login">
	<div class="form-group">
		<label for="login">Login</label>
		<input type="text" class="form-control" id="login" name="login" placeholder="Login">
	</div>
	<div class="form-group">
		<label for="password">Password</label>
		<input type="password" class="form-control" id="password" name="password" placeholder="Password">
	</div>
	<button type="submit" class="btn btn-default">Submit</button>
</form>