<h1>Register</h1>
<form method="POST">
	<input type="hidden" name="action" value="register">
	<div class="form-group">
		<label for="login">Login</label>
		<input type="text" class="form-control" id="login" name="login" placeholder="Login">
	</div>
	<div class="form-group">
		<label for="birthdate">Birthdate</label>
		<input type="date" class="form-control" id="birthdate" name="birthdate">
	</div>
	<div class="form-group">
		<label for="email">Email address</label>
		<input type="email" class="form-control" id="email" name="email" placeholder="Email">
	</div>
	<div class="form-group">
		<label for="avatar">Avatar</label>
		<input type="url" class="form-control" id="avatar" name="avatar" placeholder="Url">
	</div>
	<div class="form-group">
		<label for="password1">Password</label>
		<input type="password" class="form-control" id="password1" name="password1" placeholder="Password">
	</div>
	<div class="form-group">
		<label for="password2">Retype Password</label>
		<input type="password" class="form-control" id="password2" name="password2" placeholder="Password">
	</div>
	<button type="submit" class="btn btn-default">Submit</button>
</form>