<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" type="text/css" href="public/styles/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="public/styles/bootstrap-theme.min.css">
		<link rel="stylesheet" type="text/css" href="public/styles/style.css">
		<script type="text/javascript" src="public/scripts/jquery.js"></script>
		<script type="text/javascript" src="public/scripts/bootstrap.min.js"></script>
		<title>Multi Tchat</title>
	</head>
	<body>
		<?php require('apps/header.php'); ?>
		<?php require('apps/container.php'); ?>
		<?php require('apps/footer.php'); ?>
	</body>
</html>