
<div class="container">
	<div class="row " style="padding-top:40px;">
	    <h3 class="text-center" >BOOTSTRAP CHAT EXAMPLE </h3>
	    <br /><br />
	    <div class="col-md-8">
	        <div class="panel panel-info">
	            <div class="panel-heading">
	                <?php
	require("apps/errors.php");
	require("apps/".$page.".php");

	?>
	            </div>

			</div>
		</div>
	</div>
</div>