<div class="row">
<div class="col-sm-12">
</div><!-- /col-sm-12 -->
</div><!-- /row -->
<div class="row">
<div class="col-sm-1">
<div class="thumbnail">
<img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
</div><!-- /thumbnail -->
</div><!-- /col-sm-1 -->

<div class="col-sm-12">
<div class="panel panel-default">
<div class="panel-heading">
<strong><?=htmlentities($comments['login'])?></strong> <span class="text-muted">commented <?=$comments['date']?></span>
</div>
<div class="panel-body">
<?=htmlentities($comments['content'])?>
</div><!-- /panel-body -->
</div><!-- /panel panel-default -->
</div><!-- /col-sm-5 -->


</div><!-- /row -->

