<div class="panel-body">
<ul class="media-list">

<li class="media">

        <div class="media-body">

            <div class="media">
                <a class="pull-left" href="#">
                  <div class="avatar circle">
                    <img class="media-object img-circle " src="<?=htmlentities($message['avatar'])?>" />
                    </div>
                </a>
                <div class="media-body" >
                   <?=htmlentities($message['content'])?>
               </br>
                   <small class="text-muted"><?=htmlentities($message['login'])?> <?=$message['date']?></small>
                    <hr />
                </div>
            </div>

        </div>
    </li>
</ul>
 </div>