<h1>Register</h1>
<form method="POST">
	<input type="hidden" name="action" value="register">
	<div class="form-group">
		<label for="login">Identifiant</label>
		<input type="text" class="form-control" id="login" name="login" placeholder="Login">
	</div>
	<div class="form-group">
		<label for="birthdate">Date de naissance</label>
		<input type="date" class="form-control" id="birthdate" name="birthdate">
	</div>
	<div class="form-group">
		<label for="email">Adresse email</label>
		<input type="email" class="form-control" id="email" name="email" placeholder="Email">
	</div>
	<div class="form-group">
		<label for="password1">Mot de passe</label>
		<input type="password" class="form-control" id="password1" name="password1" placeholder="Password">
	</div>
	<div class="form-group">
		<label for="password2">Valider mot de passe</label>
		<input type="password" class="form-control" id="password2" name="password2" placeholder="Password">
	</div>
	<button type="submit" class="btn btn-default">Envoyer</button>
</form>