<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" type="" href="css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="css/bootstrap-theme.css">
		<script src="js/jquery-3.1.1.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<title>Make Chat Great Again - Chat-ouille</title>
	    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
		<link href="https://fonts.googleapis.com/css?family=Luckiest+Guy|Open+Sans+Condensed:300" rel="stylesheet">	    <meta name="description" content="" />
	    <meta name="author" content="" />
		<style> 
		
		img {
			width: 100%;
		}
		.container{
			width:900px;
			background-color: white;
			margin: 0 auto;
		}

		.form-control{
			width: 50%;
		}
	
		.avatar{
			width: 100px; 
			height: 100px;

		}
		.content{
			background-color:#394F66;
			padding: 10px;
			border-radius: 10px;
		}
		.media{
			background-color: white;
			border-radius: 10px ;
			padding: 10px;

		}
		.panel{
			border:none;
		}

		h1{
			color: white;
			font-family: 'Luckiest Guy';
			padding-left: 20px;
		}
		hr{
			border:none;
			border-top: 1px solid #1EB9BD;
		}

		.media-body{
			color: #1EB9BD;
		}
		
	


		</style>
	</head>
	<body>
		<?php require('apps/header.php'); ?>
		<?php require('apps/container.php'); ?>
		<?php require('apps/footer.php'); ?>



	</body>
</html>