<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" type="" href="css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="css/bootstrap-theme.css">
		<script src="js/jquery-3.1.1.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<title>Make Chat Great Again - Chat-ouille</title>
	    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
	    <meta name="description" content="" />
	    <meta name="author" content="" />
		<style> 
		
	
		.container{
			width:900px;
			background-color: white;
			margin: 0 auto;
		}

		.form-control{
			width: 50%;
		}
	
	.avatar{
		border: 1px solid black;
		width: 100px; 
		height: 100px;
	}
	


		</style>
	</head>
	<body>
		<?php require('apps/header.php'); ?>
		<?php require('apps/container.php'); ?>
		<?php require('apps/footer.php'); ?>



	</body>
</html>