<li class="media">
    <div class="media-body">
        <div class="media">
            <a class="pull-left" href="#">
              <div class="avatar">
                <img class=" img-circle" style="max-height:40px;" src="<?=htmlentities($users['avatar'])?>" />
              </div>
            </a>
            <div class="media-body" >
                <h5><?=htmlentities($users['login'])?></h5>               
             
            </div>
        </div>
    </div>
</li>